/**
 * TicketLedger workflow data, taken verbatim from flow.html (modules, steps, labels, decisions, links,
 * overview positions). Do not edit labels or step order here: this is the source the explorer renders.
 * Generated by extracting flow.html's data block; only the wrapper function and the returned object are new.
 */
export function buildWorkflowData() {
const S = (actor, title, note, detail) => ({actor, title, note, detail});
  const flows = [
    {
      id:'signup', group:'Account & access', label:'Sign-up & email verification', basis:'Documented behavior · 6 October 2026 · successful path',
      steps:[
        S('Browser','Submit sign-up','Name, email, phone, password','Signup.jsx validates the form; AuthContext.signup sends POST /api/auth/signup.'),
        S('API','Validate details','Normalize email and phone','authController.signup validates with Zod; duplicate accounts return 409.'),
        S('Database','Save pending user','PENDING_VERIFICATION','The API hashes the password with bcrypt and creates a pending User.'),
        S('Email service','Send verification code','6 digits · 10-minute expiry','issueOtp stores an HMAC of the code, cancels older codes, and sends the OTP email.'),
        S('Browser → API','Check entered code','Maximum 5 attempts','VerifyOtp.jsx calls /verify-otp; consumeOtp checks expiry, attempts, and single use.'),
        S('Database','Activate account','User → ACTIVE','A valid OTP is consumed; the user status and emailVerifiedAt are updated.'),
        S('API → Browser','Start session','Access token + refresh cookie','startSession returns a 15-minute access token and sets the httpOnly refresh cookie.')
      ]
    },
    {
      id:'login', group:'Account & access', label:'Login & protected access', basis:'Documented behavior · 6 October 2026 · active account',
      steps:[
        S('Browser','Submit credentials','POST /api/auth/login','The browser sends the email and password to the authentication API.'),
        S('API','Check password','bcrypt comparison','Unknown email and wrong password both return the same 401 response.'),
        S('API + Database','Check account status','Active / pending / blocked','Blocked accounts receive 403; pending accounts are sent to OTP verification.'),
        S('API → Browser','Issue session','Token in memory; cookie set','For an active account, the API creates a refresh-token row and returns the access token.'),
        S('API + Database','Link guest activity','Session ID → user ID','trackLogin links anonymous BehaviorEvent rows to the signed-in user.'),
        S('Browser → API','Request protected data','Authorization: Bearer token','The browser adds the in-memory access token to the protected API request.'),
        S('API','Check user and role','authenticateJWT → requireRole','The API reloads the user and enforces role permissions before allowing the action.')
      ]
    },
    {
      id:'refresh', group:'Account & access', label:'Restore & refresh session', basis:'Documented behavior · 6 October 2026 · valid refresh cookie',
      steps:[
        S('Browser','Restore session','Page load or token expiry','AuthContext.refreshSession runs on startup or before access-token expiry; idle sessions sign out.'),
        S('Browser → API','Send refresh cookie','POST /api/auth/refresh','The browser automatically includes the httpOnly tl_refresh cookie.'),
        S('API + Database','Find hashed token','SHA-256 lookup','rotateRefreshToken checks the stored token, expiry, revocation, and idle limit.'),
        S('Database','Rotate refresh token','Revoke old; create new','A conditional update lets only one concurrent rotation win; a new token row is created.'),
        S('API → Browser','Return new session','New cookie + access token','The API replaces the refresh cookie and returns the current user and access token.'),
        S('Browser','Resume request','Retry at most once','The browser keeps the access token in memory; an expired-token request can be retried once.')
      ]
    },
    {
      id:'reset', group:'Account & access', label:'Forgot password & reset', basis:'Documented behavior · 6 October 2026 · eligible account',
      steps:[
        S('Browser → API','Request password reset','POST /forgot-password','The user submits an email; the endpoint always returns a generic response.'),
        S('API → Email','Issue reset code','RESET_PASSWORD OTP','For an eligible account, the API creates a reset OTP and sends the email.'),
        S('Browser → API','Submit code + password','POST /reset-password','The user enters the reset code and new password.'),
        S('API','Consume valid OTP','Single use + expiry checks','consumeOtp validates the reset code before the password can be updated.'),
        S('Database','Update password hash','Revoke all refresh tokens','The API stores the new hash and revokes every refresh session.'),
        S('Browser','Sign in again','Use the new password','Existing refresh sessions no longer work; users must authenticate again.')
      ]
    },
    {
      id:'invite', group:'Account & access', label:'Gate-staff invitation', basis:'Documented behavior · 6 October 2026 · invitation accepted',
      steps:[
        S('Organizer','Invite gate staff','POST /api/staff/invites','The organizer requests a staff invitation for their company and event assignments.'),
        S('Database','Store invitation','Hashed token · 72 hours','A StaffInvite stores the hash of a random invitation token.'),
        S('Email service','Deliver invite link','/invite/<token>','The invitation email gives the recipient a link to AcceptInvite.jsx.'),
        S('Browser → API','Accept invitation','POST /accept-invite','The recipient opens the link, loads invitation details, and submits acceptance.'),
        S('Database','Create staff + assignment','Single transaction','The invite becomes ACCEPTED; a verified GATE_STAFF user and StaffEventAssignment are created.'),
        S('API → Browser','Start staff session','Company and role attached','The API issues the staff session, with event access controlled by their assignments.')
      ]
    },
    {
      id:'logout', group:'Account & access', label:'Logout & idle expiry', basis:'Documented behavior · 6 October 2026',
      steps:[
        S('Browser','Logout triggered','Manual or 30-minute idle','AuthContext.logout runs after a user action or the client idle check.'),
        S('Browser → API','Request logout','POST /api/auth/logout','The browser sends the logout request with its refresh cookie.'),
        S('API + Database','Revoke refresh token','revokeRefreshToken','The current refresh-token row is revoked so it cannot create a new access token.'),
        S('Browser','Clear local session','Signed-out view','The browser drops its current session state and shows the signed-out experience.'),
        S('API','Refuse future refresh','Expired / idle / revoked → 401','The server also rejects refresh tokens older than the allowed idle window, independently of client checks.')
      ]
    },
    {
      id:'company', group:'Tickets & event operations', label:'Company registration & approval', basis:'Planned flow · project scope · simplified approval path',
      steps:[
        S('Organizer','Register company','Company details + documents','The organizer supplies the company information required for approval.'),
        S('API','Validate submission','Required fields and documents','The submission is checked before being stored for review.'),
        S('Database','Save pending request','Awaiting admin review','The company registration remains pending until an administrator reviews it.'),
        S('Super admin','Review application','Approve or reject','The administrator checks the submitted registration and records a decision.'),
        S('Organizer','Receive approval','Event management enabled','In the approval path, the organizer can proceed to manage company events.')
      ]
    },
    {
      id:'publish', group:'Tickets & event operations', label:'Create & publish an event', basis:'Planned flow · project scope and venue requirements',
      steps:[
        S('Organizer','Enter event details','Category, venue, date','The organizer sets the event information and selects its category.'),
        S('Organizer','Add event images','Card, hero and gallery','The event receives the images used across listing and detail views.'),
        S('Venue editor','Configure enclosures','Rows, seats and aisles','The organizer uses a category template or uploaded plan to define the seating layout.'),
        S('Organizer','Set ticket prices','Enclosure and tier prices','Prices and quantities are configured for the available enclosures and tiers.'),
        S('API + Database','Save event configuration','Event + seating + tiers','The event configuration is saved for review and publication.'),
        S('Attendee view','Show published event','Browse → event details','After publication, attendees can discover the event and open its venue plan.')
      ]
    },
    {
      id:'seats', group:'Tickets & event operations', label:'Venue plan → seats → checkout', basis:'Planned flow · supplied venue requirements · successful selection',
      steps:[
        S('Attendee','Open event','Get tickets','The attendee opens the event and enters its booking flow.'),
        S('Venue overview','Choose enclosure','Name, price and availability','The attendee taps an enclosure directly on the interactive venue plan.'),
        S('Seat map','Zoom into enclosure','Rows + seat numbers','The chosen enclosure expands, while other areas dim; the attendee can return to the overview.'),
        S('Attendee','Select available seats','Available → selected','Selections stay preserved when moving between the enclosure and stadium views.'),
        S('API + Seat holds','Hold seats temporarily','Check availability','The server reserves available seats for checkout; conflicting selections must be rejected.'),
        S('My Tickets','Review selected seats','Seats + prices','The attendee reviews the chosen tickets before proceeding.'),
        S('Checkout','Confirm order','Continue to payment','The attendee confirms the order and moves into the payment workflow.')
      ]
    },
    {
      id:'payment', group:'Tickets & event operations', label:'Payment → ticket → QR wallet', basis:'Planned flow · project scope · successful payment and issuance',
      steps:[
        S('Attendee','Choose payment method','Card or mobile wallet','The attendee chooses an available payment method for the confirmed order.'),
        S('Payment provider','Process payment','Order reference + amount','The payment provider processes the payment and returns its result.'),
        S('API','Verify payment result','Match order and amount','The backend validates payment confirmation before completing ticket issuance.'),
        S('Database','Record paid order','Store payment reference','The successful payment is recorded against the order.'),
        S('Blockchain','Record ticket ownership','Planned integration','The project scope calls for blockchain-backed ticket ownership; this step is a planned flow.'),
        S('Ticket service','Create digital ticket','Ticket + unique QR','The ticket is associated with the attendee and its QR information.'),
        S('Attendee wallet','Show purchased ticket','My tickets + PDF','The attendee can view the ticket in the QR wallet and download the ticket document.')
      ]
    },
    {
      id:'gate', group:'Tickets & event operations', label:'QR scan → gate entry', basis:'Planned flow · project scope · valid, unused ticket',
      steps:[
        S('Gate staff','Scan attendee QR','Assigned event','An authorized staff member scans the ticket at the event entrance.'),
        S('API','Validate QR','Ticket and event checks','The system checks the QR information against the requested event.'),
        S('Database','Check ticket status','Valid and not already used','The ticket record must be eligible for entry and must not already be checked in.'),
        S('Blockchain','Verify ownership','Planned second validation','The scope calls for ownership verification against the blockchain record.'),
        S('API + Database','Record check-in','Prevent repeated entry','A successful check-in records ticket use; a duplicate or invalid ticket is rejected.'),
        S('Gate screen','Allow entry','Show scan result','The staff screen shows the result so the attendee can enter.')
      ]
    },
    {
      id:'resale', group:'Tickets & event operations', label:'Controlled ticket resale', basis:'Planned flow · project scope · resale cap is 110% of original price',
      steps:[
        S('Ticket holder','List ticket for resale','Owned, eligible ticket','The ticket holder chooses an eligible ticket and proposes a resale price.'),
        S('API / Contract','Check resale limit','Price ≤ original × 1.10','The planned resale rule rejects prices above 110% of the original price.'),
        S('Marketplace','Publish listing','Ticket and asking price','A valid listing becomes available to potential buyers.'),
        S('Buyer → Payment','Purchase listed ticket','Payment confirmation','The buyer completes payment for the listed ticket.'),
        S('API + Blockchain','Transfer ownership','Record new holder','The planned ownership transfer updates the ticket record and blockchain ownership.'),
        S('Buyer wallet','Show acquired ticket','Listing closed','The acquired ticket appears in the new holder’s wallet and the listing closes.')
      ]
    },
    {
      id:'tracking', group:'Behavior & analytics', label:'Behavior tracking & guest linking', basis:'Documented behavior · 6 October 2026 · event-view path',
      steps:[
        S('Browser','View an event','EventDetails.jsx','Opening an event page triggers the event request and client behavior tracking.'),
        S('Browser → API','Send behavior event','POST /api/behavior/track','trackClientBehavior sends the action with the client session identifier.'),
        S('API','Prepare activity record','trackBehavior','The service includes action, session, user when available, event, and request metadata.'),
        S('Database','Insert BehaviorEvent','Activity history','Client and server tracking can both record the same view, producing duplicate rows.'),
        S('Authentication','Link guest after login','attachSessionToUser','After authentication, anonymous rows for that session are attached to the user.'),
        S('Analytics pages','Read recorded history','Profile and funnels','Analytics aggregate these rows when a page loads; there is no scheduled analysis job.')
      ]
    },
    {
      id:'profile', group:'Behavior & analytics', label:'Behavior profile & fallback scores', basis:'Documented behavior · 6 October 2026 · fallback path currently used',
      steps:[
        S('Browser','Open behavior profile','GET /api/behavior/profile','Profile.jsx or BehaviorProfile.jsx requests the signed-in user’s profile.'),
        S('API + Database','Load recent activity','Latest 100 rows','getUserBehavioralProfile attaches the session and loads the latest behavior rows.'),
        S('API','Count recorded actions','Views, seats, checkouts','The service builds counts and feature values from the retrieved activity.'),
        S('API','Attempt model calls','Undefined function names','predictPurchaseIntent and predictFraud do not exist in mlService.js; their errors are caught.'),
        S('API','Use fallback scores','Rule-based intent; fraud 14','The current profile uses a fallback intent formula and a fixed fraud score of 14 / LOW.'),
        S('Browser','Display profile','Timeline + scores','The profile displays these values; they are not model predictions in this documented path.')
      ]
    },
    {
      id:'intent', group:'Behavior & analytics', label:'Purchase-intent analytics', basis:'Documented behavior · 6 October 2026 · rules, not model output',
      steps:[
        S('Organizer','Open intent dashboard','Select an event','PurchaseIntentAnalytics.jsx requests /api/analytics/intent/:eventId.'),
        S('API','Check event ownership','Organizer or super admin','The service verifies that the requester can view this event’s analytics.'),
        S('Database','Read activity + orders','All rows for the event','BehaviorEvent records and event orders are loaded for aggregation.'),
        S('API','Group by visitor','userId or sessionId','Actions are grouped per person; successful orders identify buyers.'),
        S('API','Build funnel and scores','Hand-written rules','getEventIntentAnalytics calculates funnel stages and intent scores using fixed rules.'),
        S('Organizer dashboard','Show intent results','Funnel + likely buyers','The page displays conversion stages, likely buyers, and abandoned users.')
      ]
    },
    {
      id:'abandoned', group:'Behavior & analytics', label:'Abandoned checkout → reminder', basis:'Documented behavior · 6 October 2026 · organizer-triggered reminder',
      steps:[
        S('Organizer','Open abandoned dashboard','GET /api/analytics/abandoned','AbandonedIntentDashboard.jsx requests the organizer’s permitted event data.'),
        S('API + Database','Find unfinished journeys','Selections or checkout starts','The service groups behavior by person and event, then excludes records it classifies as buyers.'),
        S('API','Apply recovery rules','Score, reason and cart value','Scores and likely reasons use rules; missing cart values can use the documented fallback.'),
        S('Organizer','Choose a reminder','Registered user','The organizer clicks Send reminder; guest sessions cannot receive these user reminders.'),
        S('Notification service','Store notification','dispatchNotification','The service creates a Notification row and triggers the configured delivery channels.'),
        S('Email / Socket','Attempt delivery','Email, socket; mock push','Email depends on preferences; Socket.IO emits an update and push delivery is mocked.'),
        S('Attendee','See reminder','Header polling or email','The documented UI checks notifications by polling; reminder discount text is not a working checkout coupon.')
      ]
    },
    {
      id:'demand', group:'Behavior & analytics', label:'Pre-launch demand forecast', basis:'Documented behavior · 6 October 2026 · model available; error fallback noted',
      steps:[
        S('Organizer','Open demand forecast','DemandForecast.jsx','The page requests /api/events/:id/prelaunch-forecast for the selected event.'),
        S('API + Database','Prepare event features','Capacity, price, type, city','getPreLaunchDemandForecast reads the event and prepares demand inputs.'),
        S('Node → Python','Request forecast','POST /forecast/demand','mlService.forecastEventDemand sends the features to the FastAPI service.'),
        S('Python model','Predict demand','Sales + demand tier','With compatible models loaded, the pipeline produces the forecast; missing models may use Python heuristics.'),
        S('Node API','Resolve forecast result','Model result or fallback','If the HTTP call fails, Node falls back to projected sales equal to 78% of capacity.'),
        S('Node API','Add guidance','Rule-based time and pricing','Publish-time suggestions and price warnings are calculated with separate rules.'),
        S('Organizer dashboard','Display forecast','Review or adjust prices','The results support organizer decisions; the forecast does not automatically enforce changes.')
      ]
    },
    {
      id:'fraud', group:'Behavior & analytics', label:'Fraud scoring API & watchlist', basis:'Documented behavior · 6 October 2026 · API flow; no web scoring caller',
      steps:[
        S('API client','Submit telemetry','POST /api/ml/fraud/score','This endpoint exists, but the documented web app does not call it.'),
        S('Node API','Prepare fraud features','checkFraudRisk','The service maps telemetry into the input expected by the Python fraud endpoint.'),
        S('Python / Node','Calculate risk','Model or Node heuristic','The Python model can score the request; failed calls use the Node fallback rules.'),
        S('Database','Store evaluation','AI_BOT_EVALUATION','The API stores the result as a BehaviorEvent and may create a scalper-flag audit record.'),
        S('Admin dashboard','Show fraud watchlist','Stored evaluations','The watchlist reads these stored evaluations; an administrator reviews the result.'),
        S('Super admin','Decide account action','Manual freeze or unfreeze','Freezing suspends the account and revokes refresh sessions; it is an administrator’s decision.')
      ]
    }
  ];

  flows.unshift({id:'authentication',group:'Account & access',label:'Authentication',basis:'Account lifecycle · example: login, protected access, then logout',steps:[]});
  flows.push({id:'session',group:'Account & access',label:'Start a session',basis:'Documented behavior · 6 October 2026',steps:[
    S('API','Account authenticated','startSession','A successful login, verification, or accepted invite can start a session.'),
    S('API','Create refresh token','Random 48-byte token','The session service creates the refresh token used to restore access.'),
    S('Database','Store token hash','SHA-256','The database stores the refresh-token hash, rather than the raw cookie value.'),
    S('API → Browser','Set refresh cookie','httpOnly cookie','The API sets tl_refresh, scoped to /api/auth; its nominal lifetime is seven days.'),
    S('API → Browser','Return access token','15-minute JWT','The browser keeps the access token in memory and sends it with protected requests.')
  ]});
  flows.push({id:'access',group:'Account & access',label:'Protected access & roles',basis:'Documented behavior · 6 October 2026',steps:[
    S('Browser → API','Send protected request','Bearer access token','The browser sends its in-memory access token in the Authorization header.'),
    S('API','Verify access token','authenticateJWT','The middleware verifies the JWT and its access-token type.'),
    S('API + Database','Load current user','Status checked each request','The API reloads the user so blocked statuses are enforced on protected requests.'),
    S('API','Check allowed role','requireRole','The route checks whether the current user has an allowed role.'),
    S('API','Run requested action','Authorized request','Only a permitted request reaches the protected handler.')
  ]});
  const specs={
    signup:{input:[0,3,4],links:{6:'session'},decisions:{1:{label:'Details valid?',no:'Correct details',retry:0,detail:'Invalid details or duplicate accounts must be corrected before sign-up continues.'},4:{label:'Code valid?',no:'Code rejected',retry:4,detail:'Invalid or expired codes do not activate the account; attempt limits also apply.'}},end:'Signed in'},
    login:{input:[0],links:{3:'session',4:'tracking',5:'access',6:'access'},decisions:{1:{label:'Password correct?',no:'Login error',retry:0,detail:'Unknown email and wrong password receive the same 401 response.'},2:{label:'Account active?',no:'Verify or deny',detail:'Pending users are directed to verification; blocked users receive 403.'}},end:'Access granted'},
    refresh:{input:[1,4],links:{5:'access'},decisions:{2:{label:'Refresh valid?',no:'Sign in again',target:'login',detail:'Missing, expired, idle, or revoked tokens cannot restore the session.'}},end:'Session restored'},
    reset:{input:[0,1,2],links:{5:'login'},decisions:{3:{label:'Reset code valid?',no:'Reset rejected',retry:2,detail:'A valid, unconsumed reset code is required before changing the password.'}},end:'Reset complete'},
    invite:{input:[0,2,3],links:{5:'session'},decisions:{3:{label:'Invite accepted?',no:'No new account',detail:'An expired or invalid invitation cannot be used to create a staff session.'}},end:'Staff signed in'},
    company:{input:[0],decisions:{3:{label:'Admin approves?',no:'Registration rejected',detail:'A rejected application does not enable organizer event management.'}},end:'Company approved'},
    publish:{input:[0,1,2,3],end:'Event published'},
    seats:{input:[0,1,2,3,5,6],links:{6:'payment'},decisions:{4:{label:'Seats available?',no:'Choose other seats',retry:3,detail:'A conflicting seat request must not create a new hold.'}},end:'Order ready'},
    payment:{input:[0,1,6],decisions:{2:{label:'Payment verified?',no:'Payment not confirmed',detail:'Ticket issuance must wait for valid payment confirmation.'}},end:'Ticket available'},
    gate:{input:[0,5],decisions:{1:{label:'QR valid?',no:'Reject QR',detail:'Invalid QR information must not authorize gate entry.'},2:{label:'Ticket unused?',no:'Reject repeat entry',detail:'A ticket already used for entry must not pass a second time.'},3:{label:'Owner verified?',no:'Reject ownership',detail:'This second validation is part of the planned blockchain integration.'}},end:'Attendee enters'},
    resale:{input:[0,2,3,5],decisions:{1:{label:'Price within cap?',no:'Listing rejected',retry:0,detail:'The planned limit is 110% of the original ticket price.'}},end:'New holder owns ticket'},
    tracking:{input:[0,1],end:'Activity recorded'},
    profile:{input:[0,5],end:'Profile displayed'},
    intent:{input:[0,5],decisions:{1:{label:'Access permitted?',no:'Access denied',detail:'Organizers must own the event; super-admin access is also permitted.'}},end:'Analytics displayed'},
    abandoned:{input:[0,3,6],end:'Reminder delivered'},
    demand:{input:[0,2,6],end:'Forecast displayed'},
    fraud:{input:[0,4],end:'Admin reviews result'},
    session:{input:[3,4],end:'Session active'},
    access:{input:[0],decisions:{1:{label:'Access token valid?',no:'401 response',target:'refresh',detail:'An expired access token can trigger a single refresh-and-retry attempt.'},2:{label:'User active?',no:'403 response',detail:'Blocked account statuses are rejected on protected requests.'},3:{label:'Role permitted?',no:'403 response',detail:'A valid session does not grant permission for every role-specific route.'}},end:'Response returned'}
  };
  const N=(id,label,kind,col,row,detail,target)=>({id,label,kind,col,row,detail,target});
  const E=(from,to,label='',route='auto')=>({from,to,label,route});
  const linearGraph=flow=>{
    const spec=specs[flow.id]||{},nodes=[N('start','Start','terminal',0,0,'Begin '+flow.label.toLowerCase()+'.')],edges=[],trace=['start'];
    flow.steps.forEach((s,i)=>{
      const d=(spec.decisions||{})[i],target=(spec.links||{})[i];
      nodes.push(N('s'+i,d?d.label:s.title,d?'decision':(spec.input||[]).includes(i)?'input':'process',0,i+1,s.detail,target));
      trace.push('s'+i);
      if(d)nodes.push(N('no'+i,d.no,d.target?'process':d.retry!==undefined?'input':'terminal',1,i+1,d.detail,d.target));
    });
    nodes.push(N('end',spec.end||'End','terminal',0,flow.steps.length+1,'End of this illustrated path.'));trace.push('end');
    for(let i=0;i<trace.length-1;i++){
      const source=nodes.find(n=>n.id===trace[i]);edges.push(E(trace[i],trace[i+1],source.kind==='decision'?'Yes':''));
    }
    for(const [i,d] of Object.entries(spec.decisions||{})){
      edges.push(E('s'+i,'no'+i,'No'));
      if(d.retry!==undefined)edges.push(E('no'+i,'s'+d.retry,'Retry','return-right'));
    }
    return{nodes,edges,trace};
  };
  const graphs=new Map(flows.map(f=>[f.id,linearGraph(f)]));
  graphs.set('authentication',{
    nodes:[
      N('start','Start','terminal',0,0,'An existing user opens TicketLedger.'),
      N('login','Login','input',0,1,'Open the detailed login and protected-access workflow.','login'),
      N('allowed','Login allowed?','decision',0,2,'The credentials and account status must permit access.'),
      N('denied','Access denied','terminal',1,2,'Incorrect credentials or a blocked account prevent this login path.'),
      N('session','Start session','process',0,3,'Create the refresh session and issue the browser access token.','session'),
      N('use','Protected access','process',0,4,'Protected requests verify the access token, current user status, and permitted role.','access'),
      N('logout-question','Logout clicked?','decision',0,5,'Yes opens the logout path; otherwise the session can continue.'),
      N('logout','Logout','process',1,5,'Click this Logout box to open its own animated module workflow.','logout'),
      N('signed-out','Signed out','terminal',1,6,'The local session is cleared and the user sees the signed-out experience.'),
      N('refresh-question','Refresh needed?','decision',0,6,'The browser refreshes near access-token expiry or after an expired-token response.'),
      N('refresh','Refresh session','process',0,7,'Open token validation, rotation, and request retry.','refresh')
    ],
    edges:[E('start','login'),E('login','allowed'),E('allowed','session','Yes'),E('allowed','denied','No'),E('session','use'),E('use','logout-question'),E('logout-question','logout','Yes'),E('logout','signed-out'),E('logout-question','refresh-question','No'),E('refresh-question','refresh','Yes'),E('refresh-question','use','No','return-left'),E('refresh','use','','return-left')],
    trace:['start','login','allowed','session','use','logout-question','logout','signed-out']
  });
  graphs.set('logout',{
    nodes:[
      N('start','Logout clicked','terminal',0,0,'The user clicks Logout in the signed-in application.'),
      N('idle','30-minute idle','input',1,0,'An idle timeout can trigger the same logout action.'),
      N('request','POST /logout','input',0,1,'AuthContext.logout requests POST /api/auth/logout with the refresh cookie.'),
      N('revoke','Revoke refresh token','process',0,2,'revokeRefreshToken revokes the current stored refresh session.'),
      N('clear','Clear local session','process',0,3,'The browser removes its access token and signed-in user state.'),
      N('end','Signed out','terminal',0,4,'The signed-out view is shown; the revoked refresh session cannot restore access.')
    ],
    edges:[E('start','request'),E('idle','request','Timeout','side-to-main'),E('request','revoke'),E('revoke','clear'),E('clear','end')],
    trace:['start','request','revoke','clear','end']
  });
  // A real result branch keeps the model and fallback paths distinct.
  graphs.set('demand',{
    nodes:[
      N('start','Start','terminal',0,0,'The organizer opens Demand Forecast.'),
      N('features','Prepare event inputs','process',0,1,'The API reads capacity, pricing, event type, and city.'),
      N('request','Call ML service','input',0,2,'forecastEventDemand calls the Python /forecast/demand endpoint.'),
      N('success','Request succeeds?','decision',0,3,'A successful Python response may use a loaded model or a Python heuristic.'),
      N('fallback','78% capacity fallback','process',1,3,'If the HTTP request fails, Node uses projected sales equal to 78% of capacity.'),
      N('result','Use returned forecast','process',0,4,'Use the Python forecast result when the service request succeeds.'),
      N('guidance','Add pricing guidance','process',0,5,'Node adds rule-based timing suggestions and price warnings.'),
      N('display','Display forecast','input',0,6,'Show the forecast to the organizer; it does not automatically enforce changes.'),
      N('end','End','terminal',0,7,'The organizer reviews the forecast.')
    ],
    edges:[E('start','features'),E('features','request'),E('request','success'),E('success','result','Yes'),E('success','fallback','No'),E('result','guidance'),E('fallback','guidance','','side-to-main'),E('guidance','display'),E('display','end')],
    trace:['start','features','request','success','result','guidance','display','end']
  });

  const names={authentication:'Authentication',signup:'Sign-up & verification',login:'Login & access',refresh:'Session refresh',reset:'Password reset',invite:'Staff invitations',logout:'Logout',company:'Company approval',publish:'Event publishing',seats:'Seat selection',payment:'Payment & QR wallet',gate:'Gate entry',resale:'Ticket resale',tracking:'Behavior tracking',profile:'Behavior profile',intent:'Purchase intent',abandoned:'Abandoned checkout',demand:'Demand forecast',fraud:'Fraud scoring',session:'Start a session',access:'Protected access'};
  names.overall='Overall flow';
  const moduleCount=flows.length;
  const flowMap=new Map(flows.map(f=>[f.id,f]));
  const O=(id,x,y)=>({...N(id,names[id],'process',0,0,flowMap.get(id).basis,id),x,y});
  const OE=(from,to,detail,extra={})=>({...E(from,to),detail,...extra});
  const overview={
    nodes:[O('signup',110,65),O('authentication',355,65),O('login',600,65),O('session',845,65),O('access',1090,65),O('reset',110,155),O('invite',355,155),O('refresh',845,155),O('logout',1090,155),O('company',110,282),O('publish',355,282),O('seats',600,282),O('payment',845,282),O('gate',1090,282),O('demand',355,378),O('resale',845,378),O('tracking',110,492),O('profile',355,492),O('intent',600,492),O('abandoned',845,492),O('fraud',1090,492)],
    edges:[
      OE('authentication','login','Authentication opens the login workflow. Click either module for its detailed flow.'),
      OE('login','session','Successful login starts a refresh session and issues an access token.'),
      OE('session','access','The browser uses its access token to request protected actions.'),
      OE('access','seats','An attendee can continue to event browsing and the planned seat-selection journey.',{fromSide:'right',toSide:'top',via:[[1204,65],[1204,216],[600,216]],label:'Attendee'}),
      OE('company','publish','Approved companies can manage and publish events in the planned organizer journey.'),
      OE('company','demand','Organizers can review demand while preparing an event.',{fromSide:'bottom',toSide:'left',via:[[110,378]],related:true}),
      OE('demand','publish','The forecast provides guidance before publication; changes remain an organizer decision.',{fromSide:'top',toSide:'bottom',related:true}),
      OE('publish','seats','A published event is available for attendees to browse and select seats.'),
      OE('seats','payment','A seat hold and pending order continue into payment and ticket issuance.'),
      OE('payment','gate','The issued QR ticket is used in the planned gate-entry validation flow.'),
      OE('payment','resale','A ticket holder may use the planned resale workflow.',{fromSide:'bottom',toSide:'top',related:true}),
      OE('resale','gate','The new ticket holder can present the ticket at the gate.',{fromSide:'right',toSide:'bottom',via:[[1090,378]],related:true}),
      OE('signup','session','Successful account verification can start a session without a separate login.',{fromSide:'bottom',toSide:'bottom',via:[[110,110],[845,110]],related:true}),
      OE('reset','login','After resetting a password, the user returns to login.',{fromSide:'bottom',toSide:'bottom',via:[[110,203],[600,203]],related:true}),
      OE('invite','session','Accepting a valid staff invitation can start a session.',{fromSide:'right',toSide:'bottom',via:[[510,155],[510,119],[845,119]],related:true}),
      OE('session','refresh','A refresh token allows the browser to renew its access token.',{fromSide:'bottom',toSide:'top',related:true}),
      OE('refresh','access','A successful refresh restores authorized requests.',{fromSide:'right',toSide:'left',via:[[976,155],[976,65]],related:true}),
      OE('access','logout','Choosing Logout revokes the current refresh session and clears local sign-in state.',{fromSide:'bottom',toSide:'top'}),
      OE('seats','tracking','Browsing and seat-related activity are examples of events recorded by the behavior-tracking workflow.',{fromSide:'bottom',toSide:'top',via:[[600,331],[14,331],[14,452],[110,452]],related:true}),
      OE('tracking','profile','Recorded behavior supports the behavior-profile view.',{related:true}),
      OE('tracking','intent','Purchase-intent analytics inspect recorded behavior and apply rules.',{fromSide:'bottom',toSide:'bottom',via:[[110,540],[600,540]],related:true}),
      OE('tracking','abandoned','Abandoned-checkout analysis inspects activity and can send a reminder.',{fromSide:'bottom',toSide:'bottom',via:[[110,549],[845,549]],related:true}),
      OE('tracking','fraud','Related telemetry can be submitted to the separate fraud-scoring API. The documented web app has no scoring caller.',{fromSide:'bottom',toSide:'bottom',via:[[110,558],[1090,558]],related:true,label:'Separate scoring API',labelPos:{x:1010,y:578,anchor:'middle'}})
    ],trace:[]
  };
  graphs.set('overall',overview);
  flows.unshift({id:'overall',group:'Overview',label:'Overall flow — all modules',basis:'All '+moduleCount+' modules · Solid arrows show journeys; dotted arrows show optional or supporting workflows.',steps:[]});
  flowMap.set('overall',flows[0]);
  for(const g of graphs.values())for(const n of g.nodes)if(n.target&&!flowMap.has(n.target))delete n.target;

  return {
    flows,
    graphs,
    names,
    flowMap,
    moduleCount,
    // Fixed positions of the Authentication overview flow (from flow.html's layout())
    layouts: {
      authentication: { start: [130, 100], login: [380, 100], allowed: [630, 100], session: [880, 100], use: [1130, 100], denied: [630, 232], 'logout-question': [1130, 342], logout: [880, 342], 'signed-out': [630, 342], 'refresh-question': [1130, 486], refresh: [880, 486] },
    },
    // Swim-lane labels of the overall flow (from flow.html's draw())
    lanes: { labels: [['ACCOUNT & ACCESS', 14], ['EVENTS & TICKETS', 232], ['BEHAVIOR & ANALYTICS', 442]], line: [21, 420, 1179, 420] },
    overallDescription: 'All ' + moduleCount + ' TicketLedger modules and their relationships. Click a module or choose it from the dropdown to open its flow. Dotted arrows indicate related or optional workflows.',
  };
}
